name: Build WASM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Clang
        run: sudo apt-get install -y clang lld
      
      - name: Build brain.wasm
        run: |
          clang++ --target=wasm32 \
            -O3 \
            -nostdlib \
            -Wl,--no-entry \
            -Wl,--export-all \
            -Wl,--lto-O3 \
            -Wl,--allow-undefined \
            -msimd128 \
            -o brain.wasm \
            src/brain.cpp
      
      - name: Upload WASM
        uses: actions/upload-artifact@v4
        with:
          name: brain-wasm
          path: brain.wasm
